print("--- Your Score ---")
print("Foundation English :")
FE=float(input())
print("General Business :")
GB=float(input())
print("Introduction to Computer Systems :")
ICS=float(input())
print("Computer Programming :")
CP=float(input())
print("--- Your Score ---")
print("Foundation English :",FE)
print("General Business :",GB)
print("Introduction to Computer Systems :",ICS)
print("Computer Programming :",CP)